/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package za.co.koperfontein.poc.pulsar.oidc;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
